[project]
name = "decode-validator"
authors = ["Decode Identity Solutions"]
description = "Decentralized identity validation and reputation management platform"
telemetry = false
requirements = []
[contracts.identity-validator]
path = "contracts/identity-validator.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
